### ISSUE TITLE
Add ability to define `base_locator` as class attribute

### ISSUE THREAD

**Issue by ron8mcr** [saritasa-nest/pomcorn#34]
Could you please extend `ComponentWithBaseLocator` and provide ability to define `base_locator` as class attribute like

```python
class Header(ComponentWithBaseLocator):
    base_locator = locators.ClassLocator("navigation-bar")

	def open_index_page(self):
        ...
```
Currently it's required to override `__init__` method to do this

**Comment by M1troll** [comment]
@ron8mcr I have extended `ComponentWithBaseLocator` and `ListComponent`. You can update the `pomcorn` version and try the changes.
